# -- Main Menu --

[[main]]
  name = "About"
  pageRef = "about"
  weight = 10

[[main]]
  name = "Friends"
  weight = 15

[[main]]
  name = "CHIBLY"
  parent = "Friends"
  pageRef = "friends/chibly"
  weight = 1

[[main]]
  name = "SSUGANG"
  parent = "Friends"
  pageRef = "friends/ssugang"
  weight = 2

[[main]]
  name = "Blog"
  pageRef = "blog"
  weight = 20


# -- Footer Menu --

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Authors"
#   pageRef = "authors"
#   weight = 20
