# -- Main Menu --

[[main]]
  name = "소개"
  pageRef = "about"
  weight = 10

[[main]]
  name = "친구들"
  weight = 15

[[main]]
  name = "치블리"
  parent = "친구들"
  pageRef = "friends/chibly"
  weight = 1

[[main]]
  name = "쑤깽스터"
  parent = "친구들"
  pageRef = "friends/ssugang"
  weight = 2

[[main]]
  name = "블로그"
  pageRef = "blog"
  weight = 20


# -- Footer Menu --

# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Authors"
#   pageRef = "authors"
#   weight = 20
